version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: sweetbakery-backend-db-docker
    env_file:
      - .env
    environment:
      POSTGRES_URL: ${DATABASE_URL}
    ports:
      - ${5432}:5432
